services:
  app-test:
    build:
      context: .
      dockerfile: Dockerfile.test
    environment:
      - NODE_ENV=test
      - DATABASE_URL=${DATABASE_URL_TEST}
      - WEATHER_API_KEY=${WEATHER_API_KEY_TEST}
      - SMTP_HOST=${SMTP_HOST_TEST}
      - SMTP_PORT=${SMTP_PORT_TEST}
      - SMTP_USER=${SMTP_USER_TEST}
      - SMTP_PASS=${SMTP_PASS_TEST}
      - REDIS_HOST=redis-test
      - REDIS_PORT=6379
      - APP_URL=${APP_URL_TEST}
    ports:
      - '3001:3000'

    depends_on:
      - postgres-test
      - redis-test
    volumes:
      - ./:/app
      - /app/node_modules

  postgres-test:
    image: postgres:latest
    ports:
      - '5433:5432'
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=weather_service_test
    volumes:
      - postgres-test-data:/var/lib/postgresql/data

  redis-test:
    image: redis:latest
    ports:
      - '6380:6379'
    volumes:
      - redis-test-data:/data

volumes:
  postgres-test-data:
  redis-test-data:
